### ISSUE TITLE
Cambiar referencia

### ISSUE THREAD

**Issue by ivolonte86** [eselejuanito/facebook-auto-post#1]
En cuanto a esta línea, aparece un error.
https://github.com/eselejuanito/facebook-auto-post/blob/28de54b1139f8d0adf4703da953e65cd1f340ff4/app.py#L179

La modifiqué por lo siguiente:  facebook = config_object["FACEBOOKUSER"]

Muchas gracias por el código! es un excelente aporte... lo sigo probando, espero que siga funcionando.

**Comment by eselejuanito** [comment]
Mil gracias, no habia visto tu reporte de issue, estare atento a esto y si, aun sigue fucionando, saludos.
